spring:
        profiles:
                active: dev
---
# 开发环境配置
spring:
        profiles: dev
        mqtt:
                broker:
                        id: mqtt-broker-1
                        ssl-cert-path: classpath:keystore/broker.pfx
                        ssl-password: 123456
                        multicast-group: 239.255.255.255
logging:
        level:
                root: info
                cn.recallcode.iot.mqtt.server: debug
